server:
  port: 8080

spring:
  application:
    name: tbn-backend

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  security:
    user:
      name: admin
      password: admin

# JWT 설정
jwt:
  secret: 'this-is-a-very-very-long-and-secure-secret-key-for-hs512-algorithm-1234567890!@#$%^&*()_+=-qwerty'
  expiration: 86400000 # 24시간

# CORS 설정
cors:
  allowed-origins: '*'
  allowed-methods: 'GET,POST,PUT,DELETE,OPTIONS'
  allowed-headers: '*'

# TBN 방송국 정보
tbn:
  regions:
    seoul: '서울'
    busan: '부산'
    daegu: '대구'
    incheon: '인천'
    gwangju: '광주'
    daejeon: '대전'
    ulsan: '울산'
    sejong: '세종'
    gyeonggi: '경기'
    gangwon: '강원'
    chungbuk: '충북'
    chungnam: '충남'
    jeonbuk: '전북'
    jeonnam: '전남'
    gyeongbuk: '경북'
    gyeongnam: '경남'
    jeju: '제주'
